paths:
  /notice/show:
    get:
      tags:
        - Notice
      summary: 공지사항 전체 조회
      parameters:
        - name: noticeId
          in: query
          required: false
          schema:
            properties:
              noticeId:
                type: integer
        - name: size
          in: query
          required: true
          schema:
            properties:
              size:
                type: integer
      responses:
        '200':
          description: 공지사항 조회 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: {
                  "noticeData": [
                    {
                      "userName": "KimHoon",
                      "title": "testTitle1",
                      "content": "testContent1",
                      "createdAt": "2000.01.01"
                    },
                    {
                      "userName": "HoonKim",
                      "title": "testTitle2",
                      "content": "testContent2",
                      "createdAt": "2000.02.02"
                    }
                  ],
                  "cursorId": 1
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.